# Generated by Django 4.2 on 2023-06-14 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='authenticateVoting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_authenticated_voting', models.BooleanField(default=False)),
                ('is_authenticated_editing', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='choirPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='claPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='cmaPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='mainOfficePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='sccPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voted_office_chairperson', models.BooleanField(default=False)),
                ('voted_vice_chairperson', models.BooleanField(default=False)),
                ('voted_office_secretary', models.BooleanField(default=False)),
                ('voted_vice_secretary', models.BooleanField(default=False)),
                ('voted_office_treasurer', models.BooleanField(default=False)),
                ('voted_asset_manager', models.BooleanField(default=False)),
                ('voted_scc_leader', models.BooleanField(default=False)),
                ('voted_organizing_secretary', models.BooleanField(default=False)),
                ('voted_hospitality_manager', models.BooleanField(default=False)),
                ('voted_Liturgical_leader', models.BooleanField(default=False)),
                ('voted_choir_chairperson', models.BooleanField(default=False)),
                ('voted_choir_secretary', models.BooleanField(default=False)),
                ('voted_choir_treasurer', models.BooleanField(default=False)),
                ('voted_choir_director', models.BooleanField(default=False)),
                ('voted_asst_choir_director', models.BooleanField(default=False)),
                ('voted_dancers_coordinator', models.BooleanField(default=False)),
                ('voted_dancers_secretary', models.BooleanField(default=False)),
                ('voted_worship_coordinator', models.BooleanField(default=False)),
                ('voted_cma_chairperson', models.BooleanField(default=False)),
                ('voted_cma_secretary', models.BooleanField(default=False)),
                ('voted_cla_chairperson', models.BooleanField(default=False)),
                ('voted_cla_secretary', models.BooleanField(default=False)),
                ('voted_family_chairperson', models.BooleanField(default=False)),
                ('voted_project_manager', models.BooleanField(default=False)),
                ('voted_family_secretary', models.BooleanField(default=False)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='sccCadidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadidate_name', models.CharField(max_length=100, unique=True)),
                ('cadidate_photo', models.ImageField(default='default-profile.png', upload_to='scc_cadidates')),
                ('votes', models.IntegerField(default=0)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.family')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.sccpost')),
            ],
        ),
        migrations.CreateModel(
            name='mainOfficeCadidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadidate_name', models.CharField(max_length=100, unique=True)),
                ('cadidate_photo', models.ImageField(default='default-profile.png', upload_to='main_office_cadidates')),
                ('votes', models.IntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.mainofficepost')),
            ],
        ),
        migrations.CreateModel(
            name='cmaCadidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadidate_name', models.CharField(max_length=100, unique=True)),
                ('cadidate_photo', models.ImageField(default='default-profile.png', upload_to='cma_cadidates')),
                ('votes', models.IntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.cmapost')),
            ],
        ),
        migrations.CreateModel(
            name='claCadidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadidate_name', models.CharField(max_length=100, unique=True)),
                ('cadidate_photo', models.ImageField(default='default-profile.png', upload_to='cla_cadidates')),
                ('votes', models.IntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.clapost')),
            ],
        ),
        migrations.CreateModel(
            name='choirCadidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadidate_name', models.CharField(max_length=100, unique=True)),
                ('cadidate_photo', models.ImageField(default='default-profile.png', upload_to='choir_cadidates')),
                ('votes', models.IntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.choirpost')),
            ],
        ),
    ]
