# Generated by Django 4.2 on 2023-06-14 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=100)),
                ('blog_body', models.TextField()),
                ('photo', models.ImageField(default='default-profile.png', upload_to='blogs_photos')),
            ],
        ),
        migrations.CreateModel(
            name='choirOfficeLeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leader_name', models.CharField(max_length=100)),
                ('photo', models.ImageField(default='default-profile.png', upload_to='leadership/choir_office_leaders')),
            ],
        ),
        migrations.CreateModel(
            name='claLeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leader_name', models.CharField(max_length=100)),
                ('photo', models.ImageField(default='default-profile.png', upload_to='leadership/cla_leaders')),
            ],
        ),
        migrations.CreateModel(
            name='cmaLeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leader_name', models.CharField(max_length=100)),
                ('photo', models.ImageField(default='default-profile.png', upload_to='leadership/cma_leaders')),
            ],
        ),
        migrations.CreateModel(
            name='contactUsMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=20)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='eventsPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='events_photos')),
            ],
        ),
        migrations.CreateModel(
            name='familiesPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='family_photos')),
            ],
        ),
        migrations.CreateModel(
            name='mainOfficeLeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leader_name', models.CharField(max_length=100)),
                ('photo', models.ImageField(default='default-profile.png', upload_to='leadership/main_office_leaders')),
            ],
        ),
        migrations.CreateModel(
            name='sccLeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leader_name', models.CharField(max_length=100)),
                ('photo', models.ImageField(default='default-profile.png', upload_to='leadership/scc_leaders')),
            ],
        ),
    ]
