# Generated by Django 4.2 on 2023-06-14 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sccleader',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.family'),
        ),
        migrations.AddField(
            model_name='sccleader',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.sccpost'),
        ),
        migrations.AddField(
            model_name='mainofficeleader',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.mainofficepost'),
        ),
        migrations.AddField(
            model_name='familiesphoto',
            name='family_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.family'),
        ),
        migrations.AddField(
            model_name='eventsphoto',
            name='caption',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.family'),
        ),
        migrations.AddField(
            model_name='cmaleader',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.cmapost'),
        ),
        migrations.AddField(
            model_name='claleader',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.clapost'),
        ),
        migrations.AddField(
            model_name='choirofficeleader',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.choirpost'),
        ),
    ]
