# Generated by Django 4.2 on 2023-06-15 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsphoto',
            name='caption',
            field=models.TextField(),
        ),
    ]
